version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  als-consent-oracle:
    container_name: co_als-consent-oracle
    image: mojaloop/als-consent-oracle:local
    build:
      context: .
      cache_from:
        - mojaloop/als-consent-oracle:local
    ports:
      - "3000:3000"
    networks:
      - mojaloop-net
    depends_on:
      - mysql
    environment:
      - ALS_CO_DATABASE_HOST=mysql
      - ALS_CO_DATABASE_PORT=3306
    volumes:
      - ./scripts/wait4.js:/opt/als-consent-oracle/scripts/wait4.js
      - ./scripts/wait4.config.js:/opt/als-consent-oracle/scripts/wait4.config.js
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:3008/health"]
      timeout: 20s
      retries: 10
      interval: 30s
    user: root

  mysql:
    image: mysql/mysql-server
    container_name: co_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-als-consent-oracle}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-als-consent-oracle}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
